kind: LocalConfig
apiversion: odo.dev/v1alpha1
ComponentSettings:
  Type: httpd:latest
  SourceLocation: https://github.com/openshift/jenkins.git
  Ref: release-4.5
  SourceType: git
  Ports:
  - 8080/TCP
  - 8443/TCP
  Application: jenkins
  Project: tester1
  Name: jeni
